#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::Index
properties:
  path: /properties
  controller: App\Controller\PropertiesController::Index
property:
  path: /property/{slug}/{id}
  controller: App\Controller\PropertyController::Index
admin:
  path: /admin
  controller: App\Controller\Admin\AdminPropertyController::Index
adminCreate:
  path: /admin-create
  controller: App\Controller\Admin\AdminPropertyController::New
  methods: GET|POST
adminEdit:
  path: /admin-edit/{id}
  controller: App\Controller\Admin\AdminPropertyController::Edit
  methods: GET|POST
adminDelete:
  path: /admin-delete/{id}
  controller: App\Controller\Admin\AdminPropertyController::Delete
  methods: DELETE
login:
  path: /login
  controller: App\Controller\Security\SecurityController::Login
  methods: GET|POST
signup:
  path: /signup
  controller: App\Controller\Security\SecurityController::Signup
  methods: GET|POST
logout:
  path: /logout